language: node_js
services:
  - redis-server
node_js:
   - "4.5.0"
   - "6.3.0"
script:
    - "npm run lint"
    - "npm run ava"
after_success:
  - "npm test"
  - bash <(curl -s https://codecov.io/bash)